config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  post "/pick_movie", to: "pages#pick_movie"
  post "/pick_serie", to: "pages#pick_serie"

  get "/movie/:id", to: "pages#movie_page", as: :movie
  get "/serie/:id", to: "pages#serie_page", as: :serie
end

app/views/pages/_movie.html.erb
<% if movie.present? %>
  <div>
    <%= link_to movie_path(movie["id"]) do %>
      <% if movie_poster_url.present? %>
        <%= image_tag movie_poster_url, class:"media-poster" %>
      <% else %>
        <%= image_tag "default_media_poster.jpg", class:"media-poster" %>
      <% end %>
    <% end %>
  </div>

  <div class="media-details">
    <h2><%= movie_title %></h2>
    <%= render "shared/providers", providers: movie_providers %>
    <div>
      <% if movie_length >= 60 %>
        <p class="text-grey">
          <%= hours %> h
          <%= min < 10 ? "0#{min}" : min %>
        </p>
      <% else %>
        <p class="text-grey"><%= min %> min</p>
      <% end %>
    </div>

    <div class="summary-box">
      <p class="media-summary"><%= movie_summary %></p>
    </div>
  </div>
<% end %>

app/views/pages/_serie.html.erb
<% if serie.present? %>
  <div>
    <%= link_to serie_path(serie["id"]) do %>
      <% if %>
        <%= image_tag serie_poster_url, class:"media-poster" %>
      <% else %>
        <%= image_tag "default_media_poster.jpg", class:"media-poster" %>
      <% end %>
    <% end %>
  </div>

  <div class="media-details">
    <div>
      <h2><%= serie_title %></h2>
    </div>
    <%= render "shared/providers", providers: serie_providers %>

    <div class="summary-box">
      <p class="media-summary"><%= serie_summary %></p>
    </div>
  </div>
<% end %>

app/views/pages/home.html.erb
<div id="home-container">
  <div id="monitor-container">
    <div id="monitor">
      <div id="monitor-screen">
        <div class="shutdown-flash"></div>
        <div class="media-container" id="display-media">
        </div>
      </div>
    </div>
  </div>

  <div class="remote-container" data-controller="remote">
    <div id="off-button" data-action="click->remote#togglePower">&#x23FB;</div>

    <div class="remote-media-buttons">
      <div class="remote-button button-rectangle first-rectangle"
        data-action="click->remote#toggleMedia"
        data-media-name="movies">
        Films
      </div>

      <div class="remote-button button-rectangle second-rectangle"
        data-action="click->remote#toggleMedia"
        data-media-name="series">
        Séries
      </div>
    </div>

    <button id="zap-button" data-action="click->remote#zap">
      <span class="back"></span>
      <span class="front">ZAP</span>
    </button>

    <div class="platform-buttons">
      <div class="remote-button button-square"
        data-action="click->remote#toggleProvider"
        data-provider-name="Netflix"
        style="background-image: url('<%= image_path('providers/netflix.webp') %>');"></div>
      <div class="remote-button button-square"
        data-action="click->remote#toggleProvider"
        data-provider-name="Amazon Prime Video"
        style="background-image: url('<%= image_path('providers/primevideo.webp') %>');"></div>
      <div class="remote-button button-square"
        data-action="click->remote#toggleProvider"
        data-provider-name="Canal+"
        style="background-image: url('<%= image_path('providers/canalplus.webp') %>');"></div>
      <div class="remote-button button-square"
        data-action="click->remote#toggleProvider"
        data-provider-name="TF1+"
        style="background-image: url('<%= image_path('providers/tf1.webp') %>');"></div>
      <div class="remote-button button-square"
        data-action="click->remote#toggleProvider"
        data-provider-name="Crunchyroll"
        style="background-image: url('<%= image_path('providers/crunchyroll.webp') %>');"></div>
      <div class="remote-button button-square"
        data-action="click->remote#toggleProvider"
        data-provider-name="Disney Plus"
        style="background-image: url('<%= image_path('providers/disneyplus.webp') %>');"></div>
      <div class="remote-button button-square"
        data-action="click->remote#toggleProvider"
        data-provider-name="Apple TV+"
        style="background-image: url('<%= image_path('providers/appletv.webp') %>');"></div>
      <div class="remote-button button-square"
        data-action="click->remote#toggleProvider"
        data-provider-name="Paramount Plus"
        style="background-image: url('<%= image_path('providers/paramount.webp') %>');"></div>
      <div class="remote-button button-square"
        data-action="click->remote#toggleProvider"
        data-provider-name="Max"
        style="background-image: url('<%= image_path('providers/max.webp') %>');"></div>
    </div>
  </div>
</div>

app/views/pages/movie_details.html.erb
<h1><%= params["movie"]["title"] %></h1>
<%= image_tag "https://image.tmdb.org/t/p/w300#{params["movie"]['poster_path']}" %>
<p><%= params["movie"]['overview'] %></p>
<p><%= params["movie"]['release_date'].first(4) %></p>
<p>Réalisateur : <%= image_tag @movie_director_photo_url %> <%= @movie_director %></p>
<p>Acteurs : <%= image_tag "https://image.tmdb.org/t/p/w154#{@actors[0]["profile_path"]}" %> <%= @actors[0]["name"] %>
  <%= image_tag "https://image.tmdb.org/t/p/w154#{@actors[1]["profile_path"]}" %> <%= @actors[1]["name"] %>
  <%= image_tag "https://image.tmdb.org/t/p/w154#{@actors[2]["profile_path"]}" %> <%= @actors[2]["name"] %>
</p>
<p>Catégories :
  <% params["categories"].each do |category| %>
    "<%= category['name'] %>"
  <% end %>
</p>

<% if params["length"].to_i >= 60 %>
  <p>
    <%= params["hours"].to_i %> h
    <%= params["min"].to_i < 10 ? "0#{params["min"].to_i}" : params["min"].to_i %>
  </p>
<% else %>
  <p><%= params["min"].to_i %> min</p>
<% end %>

<% case params["provider"] %>
  <% when "Disney Plus" %>
    <%= image_tag "platforms/disneyplus.png", alt: "Disney Plus Logo" %>
  <% when "Netflix" %>
    <%= image_tag "platforms/netflix.png", alt: "Netflix Logo" %>
  <% when "Apple TV+" %>
    <%= image_tag "platforms/appletv.png", alt: "Apple TV Logo" %>
  <% when "Amazon Prime Video" %>
    <%= image_tag "platforms/primevideo.png", alt: "Prime Video Logo" %>
<% end %>

app/views/pages/movie_page.html.erb
<div class="detail-show-container">
  <div class="detail-header">
    <h1><%= @movie["title"] %></h1>
  </div>

  <div class="detail-content">
    <!-- Affiche -->
    <div class="detail-left">
      <% if @movie['poster_path'].present? %>
        <%= image_tag "https://image.tmdb.org/t/p/w300#{@movie['poster_path']}", class: "detail-poster" %>
      <% end %>
    </div>

    <div class="detail-right">
      <% if @movie['overview'].present? %>
        <p class="detail-overview"><%= @movie['overview'] %></p>
        <p class="release-year">📅 <%= @movie['release_date'].first(4) %></p>
      <% end %>

      <% if @movie_director.present? %>
        <div class="director">
          🎬 Réalisateur :
          <% if @movie_director_photo_url.present? %>
            <%= image_tag @movie_director_photo_url, alt: @movie_director, class: "director-photo" %>
          <% end %>
          <span><%= @movie_director %></span>
        </div>
      <% end %>

      <% if @movie_actors.present? %>
        <div class="casting">
          <% if @movie_actors[0].present? %>
            👤 Acteurs :
            <% @movie_actors.first(3).each do |actor| %>
              <% if actor.present? %>
                <div class="actor">
                  <% if actor["profile_path"].present? %>
                    <%= image_tag "https://image.tmdb.org/t/p/w154#{actor["profile_path"]}" %>
                  <% end %>
                  <p><%= actor["name"] %></p>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <% if @movie["genres"].present? %>
        <div class="categories">
          🏷️ Catégories :
          <% @movie["genres"].each do |category| %>
            <% if category['name'].present? %>
              <span class="tag"><%= category['name'] %></span>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <% if @movie["length"].present? && @movie["min"].present? %>
        <div class="duration">
          ⏱️ Durée :
          <% if @movie["length"].to_i >= 60 %>
            <%= @movie["hours"].to_i %> h
            <%= @movie["min"].to_i < 10 ? "0#{@movie["min"].to_i}" : @movie["min"].to_i %>
          <% else %>
            <%= @movie["min"].to_i %> min
          <% end %>
        </div>
      <% end %>

      <% if @movie["provider"].present? %>
        <div class="platforms">
          📺 Disponible sur :
          <% @movie["provider"].each do |provider| %>
            <% logo = {
              "Disney Plus" => ["providers/disneyplus.webp", "Disney Plus", "https://www.disneyplus.com/fr-fr"],
              "Netflix" => ["providers/netflix.webp", "Netflix", "https://www.netflix.com"],
              "Apple TV+" => ["providers/appletv.webp", "Apple TV", "https://tv.apple.com/fr"],
              "Amazon Prime Video" => ["providers/primevideo.webp", "Amazon Prime Video", "https://www.primevideo.com"],
              "Canal+" => ["providers/canalplus.webp", "Canal+", "https://www.canalplus.com/"],
              "HBO Max" => ["providers/max.webp", "HBO Max", "https://www.hbomax.com/fr/fr"],
              "TF1+" => ["providers/tf1.webp", "TF1+", "https://www.tf1.fr"],
              "Paramount Plus" => ["providers/paramount.webp", "Paramount Plus", "https://www.paramountplus.com/fr"],
              "Crunchyroll" => ["providers/crunchyroll.webp", "Crunchyroll", "https://www.crunchyroll.com/fr"]
            }[provider] %>

            <% if logo.present? %>
              <%= link_to logo[2], target: "_blank" do %>
                <%= image_tag logo[0], alt: logo[1], class: "media-provider" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/serie_page.html.erb
<div class="detail-show-container">
  <div class="detail-header">
    <h1><%= @serie["name"] %></h1>
  </div>

  <div class="detail-content">
    <!-- Affiche -->
    <div class="detail-left">
      <%= image_tag "https://image.tmdb.org/t/p/w300#{@serie['poster_path']}" %>
    </div>

    <!-- Détails -->
    <div class="detail-right">
      <p class="detail-overview"><%= @serie['overview'] %></p>
      <p class="release-year">📅 <%= @serie['first_air_date'].first(4) %></p>

      <div class="casting">
        <% if @serie_actors[0].present? %>
          👤 Acteurs :
          <div class="actor">
            <%= image_tag "https://image.tmdb.org/t/p/w154#{@serie_actors[0]["profile_path"]}" %>
            <p><%= @serie_actors[0]["name"] %></p>
          </div>
          <% if @serie_actors[1].present? %>
            <div class="actor">
              <%= image_tag "https://image.tmdb.org/t/p/w154#{@serie_actors[1]["profile_path"]}" %>
              <p><%= @serie_actors[1]["name"] %></p>
            </div>
          <% end %>
          <% if @serie_actors[2].present? %>
            <div class="actor">
              <%= image_tag "https://image.tmdb.org/t/p/w154#{@serie_actors[2]["profile_path"]}" %>
              <p><%= @serie_actors[2]["name"] %></p>
            </div>
          <% end %>
        <% end %>
      </div>

      <% if @serie["genres"].present? %>
        <div class="categories">
          🏷️ Catégories :
          <% @serie["genres"].each do |category| %>
            <span class="tag"><%= category['name'] %></span>
          <% end %>
        </div>
      <% end %>

      <% if @serie["providers"].present? %>
        <div class="platforms">
          📺 Disponible sur :
          <% @serie["providers"].each do |provider| %>
            <% logo = {
              "Disney Plus" => ["providers/disneyplus.webp", "Disney Plus", "https://www.disneyplus.com/fr-fr"],
              "Netflix" => ["providers/netflix.webp", "Netflix", "https://www.netflix.com"],
              "Apple TV+" => ["providers/appletv.webp", "Apple TV", "https://tv.apple.com/fr"],
              "Amazon Prime Video" => ["providers/primevideo.webp", "Amazon Prime Video", "https://www.primevideo.com"],
              "Canal+" => ["providers/canalplus.webp", "Canal+", "https://www.canalplus.com/"],
              "HBO Max" => ["providers/max.webp", "HBO Max", "https://www.hbomax.com/fr/fr"],
              "TF1+" => ["providers/tf1.webp", "TF1+", "https://www.tf1.fr"],
              "Paramount Plus" => ["providers/paramount.webp", "Paramount Plus", "https://www.paramountplus.com/fr"],
              "Crunchyroll" => ["providers/crunchyroll.webp", "Crunchyroll", "https://www.crunchyroll.com/fr"]
            }[provider] %>

            <% if logo %>
              <%= link_to logo[2], target: "_blank" do %>
                <%= image_tag logo[0], alt: logo[1], class: "media-provider" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
</div>